// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaGestaoLar.Api.Data;

#nullable disable

namespace SistemaGestaoLar.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260731230552_RemoveHistoricoAcolhimentoFromMorador")]
    partial class RemoveHistoricoAcolhimentoFromMorador
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("AjudanteGrupo", b =>
                {
                    b.Property<int>("AjudantesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GruposId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AjudantesId", "GruposId");

                    b.HasIndex("GruposId");

                    b.ToTable("AjudanteGrupo", (string)null);
                });

            modelBuilder.Entity("SistemaGestaoLar.Api.Entities.Ajudante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Disponibilidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ajudantes");
                });

            modelBuilder.Entity("SistemaGestaoLar.Api.Entities.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("SistemaGestaoLar.Api.Entities.Morador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContatoEmergencia")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Moradores");
                });

            modelBuilder.Entity("SistemaGestaoLar.Api.Entities.ServicoStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServicosStatus");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Name = "Pendente"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Realizado"
                        },
                        new
                        {
                            Id = 4,
                            Name = "NaoRealizado"
                        });
                });

            modelBuilder.Entity("SistemaGestaoLar.Api.Entities.ServicoTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServicosTicket");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Name = "Jantar"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Banho"
                        },
                        new
                        {
                            Id = 4,
                            Name = "TrocaRoupas"
                        });
                });

            modelBuilder.Entity("SistemaGestaoLar.Api.Entities.TicketDiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DataServico")
                        .HasColumnType("TEXT");

                    b.Property<int>("MoradorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TicketDiarios");
                });

            modelBuilder.Entity("SistemaGestaoLar.Api.Entities.TicketServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServicoStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServicoTicketId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TicketDiarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServicoStatusId");

                    b.HasIndex("ServicoTicketId");

                    b.HasIndex("TicketDiarioId");

                    b.ToTable("TicketServicos");
                });

            modelBuilder.Entity("AjudanteGrupo", b =>
                {
                    b.HasOne("SistemaGestaoLar.Api.Entities.Ajudante", null)
                        .WithMany()
                        .HasForeignKey("AjudantesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGestaoLar.Api.Entities.Grupo", null)
                        .WithMany()
                        .HasForeignKey("GruposId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaGestaoLar.Api.Entities.TicketServico", b =>
                {
                    b.HasOne("SistemaGestaoLar.Api.Entities.ServicoStatus", "ServicoStatus")
                        .WithMany()
                        .HasForeignKey("ServicoStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGestaoLar.Api.Entities.ServicoTicket", "ServicoTicket")
                        .WithMany()
                        .HasForeignKey("ServicoTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGestaoLar.Api.Entities.TicketDiario", "TicketDiario")
                        .WithMany("Servicos")
                        .HasForeignKey("TicketDiarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServicoStatus");

                    b.Navigation("ServicoTicket");

                    b.Navigation("TicketDiario");
                });

            modelBuilder.Entity("SistemaGestaoLar.Api.Entities.TicketDiario", b =>
                {
                    b.Navigation("Servicos");
                });
#pragma warning restore 612, 618
        }
    }
}
